apiVersion: v1
kind: Service
metadata:
  name: myaws-nginx-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    targetPort: http
    protocol: TCP
  selector:
    tier: frontend